# Generated by Django 4.0 on 2022-07-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='color_code',
            field=models.CharField(default='#563d7c', max_length=100),
        ),
        migrations.AddField(
            model_name='type',
            name='color_code',
            field=models.CharField(default='#563d7c', max_length=100),
        ),
    ]
