# Generated by Django 4.0 on 2022-07-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_priority_color_code_type_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color_code',
            field=models.CharField(default='#563d7c', max_length=30),
        ),
        migrations.AlterField(
            model_name='type',
            name='color_code',
            field=models.CharField(default='#563d7c', max_length=30),
        ),
    ]
