# Generated by Django 4.0 on 2022-08-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_project_title_alter_ticket_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[['Roles', [['tester', 'Tester'], ['developer', 'Developer'], ['project_manager', 'Project Manager']]], ['Actions', [['tester', 'Inspect'], ['developer', 'Contribute'], ['project_manager', 'Manage']]]]),
        ),
    ]
