# Generated by Django 4.0 on 2022-07-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_project_color_code_alter_type_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email_disable',
            field=models.BooleanField(default=False),
        ),
    ]
