# Generated by Django 4.0 on 2022-07-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_project_archived_alter_project_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='archived',
        ),
    ]
