# Generated by Django 4.0 on 2022-07-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_project_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectArchive',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.project')),
            ],
            bases=('tickets.project',),
        ),
    ]
