# Generated by Django 4.0 on 2022-07-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_project_archive_delete_projectarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color_code',
            field=models.CharField(default='#563d7c', max_length=100),
        ),
        migrations.AlterField(
            model_name='type',
            name='color_code',
            field=models.CharField(default='#563d7c', max_length=100),
        ),
    ]
