# Generated by Django 4.0 on 2022-08-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[['tester', 'Inspect'], ['developer', 'Comply'], ['project_manager', 'Manage']]),
        ),
    ]
