# Generated by Django 4.0 on 2022-07-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_project_color_code_alter_type_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='test_status',
            field=models.BooleanField(default=False),
        ),
    ]
