# Generated by Django 4.0 on 2022-07-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_remove_user_ticket_flow_user_ticket_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ticket_flow',
            field=models.ManyToManyField(to='tickets.Project'),
        ),
    ]
