# Generated by Django 4.0 on 2022-07-23 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_alter_user_ticket_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ticket_flow',
        ),
        migrations.AddField(
            model_name='user',
            name='ticket_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.project'),
        ),
    ]
