# Generated by Django 4.0 on 2022-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_ticket_tester_alter_ticket_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ticket_flow',
        ),
        migrations.AddField(
            model_name='user',
            name='ticket_flow',
            field=models.ManyToManyField(to='tickets.Project'),
        ),
    ]
