# Generated by Django 4.0 on 2022-07-26 15:00

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_remove_user_ticket_flow_user_ticket_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ticket_flow',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='book', chained_model_field='projects', to='tickets.Project'),
        ),
    ]
