# Generated by Django 4.0 on 2022-07-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_alter_user_ticket_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ticket_flow',
            field=models.ManyToManyField(blank=True, to='tickets.Project'),
        ),
    ]
