# Generated by Django 4.0 on 2022-07-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_alter_user_ticket_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
