# Generated by Django 4.0 on 2022-07-31 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_alter_comment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='due_to',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
