# Generated by Django 4.0 on 2022-08-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0042_user_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=90, unique=True),
        ),
    ]
